# Generated by Django 5.2.15 on 2026-06-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_department_id_remove_user_faculty_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (100, "100 Level"),
                    (200, "200 Level"),
                    (300, "300 Level"),
                    (400, "400 Level"),
                    (500, "500 Level"),
                    (600, "600 Level"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (100, "100 Level"),
                    (200, "200 Level"),
                    (300, "300 Level"),
                    (400, "400 Level"),
                    (500, "500 Level"),
                    (600, "600 Level"),
                ],
                null=True,
            ),
        ),
    ]
