# Generated by Django 5.2.15 on 2026-07-01 00:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_importjob"),
        ("tenancy", "0002_institution_carryover_cgpa_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("course", "Course"),
                    ("assignment", "Assignment"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="accounts.course",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        limit_choices_to={"role": "lecturer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_assignments",
                        to="accounts.semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_assignments",
                        to="accounts.session",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_course_assignment",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lecturer", "course", "session", "semester"),
                        name="uniq_assignment_per_lecturer_course_term",
                    )
                ],
            },
        ),
    ]
