# Generated by Django 5.2.15 on 2026-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_importjob_kind_courseassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
