# Generated by Django 5.2.16 on 2026-07-11 13:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_user_rank"),
        ("tenancy", "0004_institution_classification_bands_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditorToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=200)),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "programmes",
                    models.ManyToManyField(
                        blank=True, related_name="auditor_tokens", to="accounts.programme"
                    ),
                ),
                (
                    "sessions",
                    models.ManyToManyField(
                        blank=True, related_name="auditor_tokens", to="accounts.session"
                    ),
                ),
            ],
            options={
                "db_table": "auditor_token",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditorAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=255)),
                ("resource", models.CharField(max_length=64)),
                ("detail", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_logs",
                        to="auditor.auditortoken",
                    ),
                ),
            ],
            options={
                "db_table": "auditor_access_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
