# Generated by Django 5.2.16 on 2026-07-29 10:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0005_institution_webcam_retention_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("result_returned", "Result returned to lecturer"),
                            ("result_published", "Results published (ratified)"),
                            ("exam_scheduled", "Exam scheduled"),
                            ("exam_opened", "Exam open for sitting"),
                            ("cheating_flag_raised", "Integrity flag raised"),
                            ("cheating_flag_escalated", "Integrity flag escalated"),
                            ("result_check_otp", "Result-check phone verification code"),
                            ("result_check_reply", "Result-check reply"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp")],
                        max_length=10,
                    ),
                ),
                ("recipient_address", models.CharField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("provider", models.CharField(blank=True, default="", max_length=40)),
                ("provider_message_id", models.CharField(blank=True, default="", max_length=120)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("dedupe_key", models.CharField(blank=True, default="", max_length=200)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["institution", "status"], name="notificatio_institu_dcbd88_idx"
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"], name="notificatio_recipie_a972ce_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key", ""), _negated=True),
                        fields=("institution", "dedupe_key"),
                        name="uniq_notification_dedupe_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResultCheckRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("msisdn", models.CharField(help_text="E.164, e.g. +2348030000000", max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("pin_hash", models.CharField(max_length=128)),
                ("otp_hash", models.CharField(blank=True, default="", max_length=128)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_check_registration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_result_check_registration",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_verified", True)),
                        fields=("msisdn",),
                        name="uniq_verified_msisdn",
                    )
                ],
            },
        ),
    ]
