# Generated by Django 5.2.16 on 2026-08-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("result_returned", "Result returned to lecturer"),
                    ("result_published", "Results published (ratified)"),
                    ("exam_scheduled", "Exam scheduled"),
                    ("exam_opened", "Exam open for sitting"),
                    ("cheating_flag_raised", "Integrity flag raised"),
                    ("cheating_flag_escalated", "Integrity flag escalated"),
                    ("result_check_otp", "Result-check phone verification code"),
                    ("result_check_reply", "Result-check reply"),
                    ("announcement_posted", "Course announcement posted"),
                ],
                max_length=32,
            ),
        ),
    ]
