# Generated by Django 5.2.15 on 2026-07-06 08:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_user_rank"),
        ("tenancy", "0004_institution_classification_bands_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicStanding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "term_quality_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("term_credit_units", models.PositiveSmallIntegerField(default=0)),
                ("gpa", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "cumulative_quality_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("cumulative_credit_units", models.PositiveSmallIntegerField(default=0)),
                (
                    "cgpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "standing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good standing"),
                            ("probation", "Probation"),
                            ("withdrawal", "Withdrawal"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("classification", models.CharField(blank=True, default="", max_length=50)),
                ("is_borderline", models.BooleanField(default=False)),
                ("borderline_band", models.CharField(blank=True, default="", max_length=50)),
                ("outstanding_carryovers", models.JSONField(blank=True, default=list)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_standings",
                        to="accounts.semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_standings",
                        to="accounts.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_standings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "grading_academic_standing",
                "ordering": ["student__full_name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "session", "semester"),
                        name="uniq_standing_per_student_term",
                    )
                ],
            },
        ),
    ]
