# Generated by Django 5.2.15 on 2026-07-06 08:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import assessments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_user_rank"),
        ("tenancy", "0003_institution_lecturer_ranks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("test", "Test"),
                            ("project", "Project"),
                        ],
                        max_length=12,
                    ),
                ),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("due_date", models.DateTimeField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_items",
                        to="accounts.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "lecturer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_items",
                        to="accounts.semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_items",
                        to="accounts.session",
                    ),
                ),
            ],
            options={
                "db_table": "assessments_item",
                "ordering": ["due_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to=assessments.models.submission_upload_path
                    ),
                ),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("submitted_at", models.DateTimeField()),
                ("is_late", models.BooleanField(default=False)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="assessments.assessmentitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assessments_submission",
                "ordering": ["submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("feedback", models.TextField(blank=True, default="")),
                ("is_released", models.BooleanField(default=False)),
                (
                    "graded_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "lecturer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="assessments.assessmentitem",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade",
                        to="assessments.submission",
                    ),
                ),
            ],
            options={
                "db_table": "assessments_grade",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="assessmentitem",
            constraint=models.UniqueConstraint(
                fields=("course", "session", "semester", "title"),
                name="uniq_item_title_per_course_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("item", "student"), name="uniq_submission_per_student_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentgrade",
            constraint=models.UniqueConstraint(
                fields=("item", "student"), name="uniq_grade_per_student_item"
            ),
        ),
    ]
