# Generated by Django 5.2.16 on 2026-08-01 08:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import content.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0007_user_phone_number"),
        ("tenancy", "0005_institution_webcam_retention_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_modules",
                        to="accounts.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_modules",
                        to="accounts.semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_modules",
                        to="accounts.session",
                    ),
                ),
            ],
            options={
                "db_table": "content_module",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("page", "Page"),
                            ("link", "Link"),
                            ("video", "Video"),
                        ],
                        max_length=8,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=content.models.content_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.module",
                    ),
                ),
            ],
            options={
                "db_table": "content_item",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_viewed_at", models.DateTimeField()),
                ("last_viewed_at", models.DateTimeField()),
                ("view_count", models.PositiveIntegerField(default=1)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="content.contentitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_view",
                "ordering": ["-last_viewed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "student"), name="uniq_view_per_student_item"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["course", "session", "semester", "position"],
                name="content_mod_course__97ca89_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "session", "semester", "title"),
                name="uniq_module_title_per_course_term",
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["module", "position"], name="content_ite_module__80028c_idx"
            ),
        ),
    ]
