# Generated by Django 5.2.16 on 2026-07-25 20:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_user_rank"),
        ("tenancy", "0004_institution_classification_bands_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("ca", "Continuous assessment"), ("exam", "Main exam")],
                        default="exam",
                        max_length=8,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                ("opens_at", models.DateTimeField()),
                ("closes_at", models.DateTimeField()),
                ("num_questions", models.PositiveIntegerField()),
                ("shuffle_questions", models.BooleanField(default=True)),
                ("shuffle_options", models.BooleanField(default=True)),
                (
                    "pass_mark",
                    models.DecimalField(
                        decimal_places=2, default=50, help_text="Percentage, 0–100.", max_digits=5
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="accounts.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "lecturer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="accounts.semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="accounts.session",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_exam",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("submitted", "Submitted (awaiting marking)"),
                            ("auto_submitted", "Auto-submitted (awaiting marking)"),
                            ("graded", "Graded"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "max_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                ("requires_manual_grading", models.BooleanField(default=False)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="cbt.exam",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cbt_exam_attempt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple choice (single answer)"),
                            ("multi", "Multiple select"),
                            ("true_false", "True / false"),
                            ("fill_blank", "Fill in the blank"),
                            ("short_answer", "Short answer"),
                        ],
                        max_length=16,
                    ),
                ),
                ("prompt", models.TextField()),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.JSONField(blank=True, null=True)),
                ("marks", models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ("requires_manual_grading", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("topic", models.CharField(blank=True, default="", max_length=120)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_question",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AttemptQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField()),
                ("option_order", models.JSONField(blank=True, default=list)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_questions",
                        to="cbt.examattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cbt.question",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_attempt_question",
                "ordering": ["attempt", "position"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "awarded_marks",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("graded_manually", models.BooleanField(default=False)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="cbt.examattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cbt.question",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_answer",
                "ordering": ["attempt", "question"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_banks",
                        to="accounts.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_question_bank",
                "ordering": ["title", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="cbt.questionbank",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="banks",
            field=models.ManyToManyField(related_name="exams", to="cbt.questionbank"),
        ),
        migrations.AddConstraint(
            model_name="examattempt",
            constraint=models.UniqueConstraint(
                fields=("exam", "student"), name="uniq_attempt_per_exam_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="attemptquestion",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="uniq_attempt_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="attemptquestion",
            constraint=models.UniqueConstraint(
                fields=("attempt", "position"), name="uniq_attempt_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="uniq_answer_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionbank",
            constraint=models.UniqueConstraint(
                fields=("course", "title"), name="uniq_bank_title_per_course"
            ),
        ),
    ]
