# Generated by Django 5.2.16 on 2026-07-25 22:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cbt.models


class Migration(migrations.Migration):
    dependencies = [
        ("cbt", "0001_initial"),
        ("tenancy", "0005_institution_webcam_retention_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebcamCapture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("snapshot", "Snapshot"), ("clip", "Short clip")],
                        default="snapshot",
                        max_length=10,
                    ),
                ),
                (
                    "media",
                    models.FileField(max_length=255, upload_to=cbt.models.webcam_upload_path),
                ),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("captured_at", models.DateTimeField()),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When retention lapses; media is purged by the cleanup task after this."
                    ),
                ),
                ("is_anomalous", models.BooleanField(default=False)),
                ("anomaly_reason", models.CharField(blank=True, default="", max_length=200)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webcam_captures",
                        to="cbt.examattempt",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_webcam_capture",
                "ordering": ["attempt", "captured_at"],
            },
        ),
        migrations.CreateModel(
            name="CheatingFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("raised", "Raised (awaiting review)"),
                            ("dismissed", "Dismissed (false positive)"),
                            ("escalated", "Escalated to HOD"),
                        ],
                        default="raised",
                        max_length=12,
                    ),
                ),
                ("auto_raised", models.BooleanField(default=True)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, default="")),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheating_flags",
                        to="cbt.examattempt",
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cbt_cheating_flag",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("attempt",), name="uniq_flag_per_attempt")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProctorEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "Tab switch"),
                            ("focus_loss", "Window blur / focus loss"),
                            ("focus_regain", "Focus regained"),
                            ("fullscreen_exit", "Fullscreen exit"),
                            ("copy_attempt", "Copy attempt"),
                            ("paste_attempt", "Paste attempt"),
                            ("heartbeat", "Still-present heartbeat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("client_timestamp", models.DateTimeField()),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proctor_events",
                        to="cbt.examattempt",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.institution",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_proctor_event",
                "ordering": ["attempt", "client_timestamp", "created_at"],
                "indexes": [
                    models.Index(fields=["attempt", "type"], name="cbt_proctor_attempt_229add_idx")
                ],
            },
        ),
    ]
