# Generated by Django 5.2.16 on 2026-07-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0001_initial"),
        ("cbt", "0002_webcamcapture_cheatingflag_proctorevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="assessment_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cbt_exam",
                to="assessments.assessmentitem",
            ),
        ),
    ]
