from django.urls import path

from accounts.views import (
    AssignmentImportView,
    CourseAssignmentDetailView,
    CourseAssignmentListCreateView,
    CourseDetailView,
    CourseImportView,
    CourseListCreateView,
    DepartmentDetailView,
    DepartmentListCreateView,
    EnrolmentDetailView,
    EnrolmentListCreateView,
    FacultyDetailView,
    FacultyListCreateView,
    ImportJobDetailView,
    ProgrammeDetailView,
    ProgrammeListCreateView,
    SemesterDetailView,
    SemesterListCreateView,
    SessionDetailView,
    SessionListCreateView,
    StudentImportView,
    UserDetailView,
    UserListCreateView,
)

urlpatterns = [
    path("users", UserListCreateView.as_view(), name="user-list"),
    path("users/<uuid:pk>", UserDetailView.as_view(), name="user-detail"),
    path("faculties", FacultyListCreateView.as_view(), name="faculty-list"),
    path("faculties/<uuid:pk>", FacultyDetailView.as_view(), name="faculty-detail"),
    path("departments", DepartmentListCreateView.as_view(), name="department-list"),
    path("departments/<uuid:pk>", DepartmentDetailView.as_view(), name="department-detail"),
    path("programmes", ProgrammeListCreateView.as_view(), name="programme-list"),
    path("programmes/<uuid:pk>", ProgrammeDetailView.as_view(), name="programme-detail"),
    path("sessions", SessionListCreateView.as_view(), name="session-list"),
    path("sessions/<uuid:pk>", SessionDetailView.as_view(), name="session-detail"),
    path("semesters", SemesterListCreateView.as_view(), name="semester-list"),
    path("semesters/<uuid:pk>", SemesterDetailView.as_view(), name="semester-detail"),
    path("courses", CourseListCreateView.as_view(), name="course-list"),
    path("courses/<uuid:pk>", CourseDetailView.as_view(), name="course-detail"),
    path("enrolments", EnrolmentListCreateView.as_view(), name="enrolment-list"),
    path("enrolments/<uuid:pk>", EnrolmentDetailView.as_view(), name="enrolment-detail"),
    path("assignments", CourseAssignmentListCreateView.as_view(), name="assignment-list"),
    path("assignments/<uuid:pk>", CourseAssignmentDetailView.as_view(), name="assignment-detail"),
    path("import/students", StudentImportView.as_view(), name="import-students"),
    path("import/courses", CourseImportView.as_view(), name="import-courses"),
    path("import/assignments", AssignmentImportView.as_view(), name="import-assignments"),
    path("import/jobs/<uuid:pk>", ImportJobDetailView.as_view(), name="import-job-detail"),
]
