# Generated by Django 6.0.6 on 2026-06-16 16:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=30, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "grading_scale_type",
                    models.CharField(
                        choices=[
                            ("5_POINT", "5-Point Scale"),
                            ("7_POINT", "7-Point Scale"),
                            ("4_POINT", "4-Point Scale"),
                        ],
                        default="5_POINT",
                        max_length=20,
                    ),
                ),
                ("default_ca_weight", models.PositiveSmallIntegerField(default=40)),
                ("default_exam_weight", models.PositiveSmallIntegerField(default=60)),
                ("pass_mark", models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                (
                    "probation_cgpa_threshold",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
                ("enforce_fees_for_results", models.BooleanField(default=False)),
                ("has_external_affiliation", models.BooleanField(default=False)),
                ("has_teaching_practice", models.BooleanField(default=False)),
                ("has_sponsor_portal", models.BooleanField(default=False)),
                ("primary_color", models.CharField(blank=True, default="", max_length=7)),
                ("logo_url", models.URLField(blank=True, default="")),
            ],
            options={
                "db_table": "tenancy_institution",
                "ordering": ["name"],
            },
        ),
    ]
