# Generated by Django 5.2.15 on 2026-06-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="carryover_cgpa_method",
            field=models.CharField(
                choices=[
                    ("ALL_ATTEMPTS", "All attempts count in CGPA"),
                    ("HIGHEST_ONLY", "Only the best attempt counts in CGPA"),
                ],
                default="ALL_ATTEMPTS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="carryover_pass_mark",
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AddField(
            model_name="institution",
            name="max_credit_units_per_semester",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="institution",
            name="min_credit_units_per_semester",
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
