# Generated by Django 5.2.15 on 2026-07-06 07:05

from django.db import migrations, models

import tenancy.models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_institution_carryover_cgpa_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="lecturer_ranks",
            field=models.JSONField(blank=True, default=tenancy.models.default_lecturer_ranks),
        ),
    ]
