# Generated by Django 5.2.15 on 2026-07-06 08:31

from decimal import Decimal

from django.db import migrations, models

import tenancy.models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_institution_lecturer_ranks"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="classification_bands",
            field=models.JSONField(blank=True, default=tenancy.models.default_classification_bands),
        ),
        migrations.AddField(
            model_name="institution",
            name="gpa_source_status",
            field=models.CharField(default="ratified_by_senate", max_length=20),
        ),
        migrations.AddField(
            model_name="institution",
            name="grade_scale",
            field=models.JSONField(blank=True, default=tenancy.models.default_grade_scale),
        ),
        migrations.AddField(
            model_name="institution",
            name="senate_review_margin",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.05"), max_digits=3),
        ),
        migrations.AddField(
            model_name="institution",
            name="withdrawal_cgpa_threshold",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
