# Generated by Django 5.2.16 on 2026-07-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0004_institution_classification_bands_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="webcam_retention_days",
            field=models.PositiveIntegerField(default=90),
        ),
    ]
